### ISSUE TITLE
Bad uname -r kernel version

### ISSUE THREAD

**Issue by Yes21** [RPi-Distro/pi-gen#223]
We thank you very much for this nice and very useful script.
We have modified it to build our specific version of raspbian for our project ([EZ-Wifibroadcast](https://github.com/RespawnDespair/wifibroadcast-image-builder)).

We encounter a problem that we can't solve : 
When we are in CHROOT stages, the `uname -r` command returns the kernel number of the host, but not those of the raspbian we have installed !

Did you ever had this problem, and do you know how to solve it ?

Many thanks for help.

**Comment by XECDesign** [comment]
Since uname prints system information for the currently running kernel, that's working as intended.

Here's how we're working around that:
https://github.com/RPi-Distro/pi-gen/blob/master/export-image/04-finalise/01-run.sh#L61

I'm sure you could also extract the string from the actual kernel image.

**Comment by Yes21** [comment]
Thank you very much for your fast answer.
I will look at this ...

**Comment by Yes21** [comment]
Many thanks to have pointing us into the right direction.
We could solve our problem !

**Comment by XECDesign** [comment]
Glad you found a workaround
