### ISSUE TITLE
speed improvement

### ISSUE THREAD

**Issue by FredericGuilbault** [RPi-Distro/pi-gen#272]
If the flag `BUILD=1` is set. 
Prior to start a stage, the `rootfs/` is deleted with rm.  Then, prerun.sh call `copy_previous` Witch copy vis rsync the files from the previous stage in the current one. 

Im guessing that if the rsync command in `copy_previous` would have the flag --delete. 
 - Files from the previous stages would stay, 
 - changed files would be overwriten, 
 - Added files would be deleted. 

Instead of rm all the file system and rewriting most of them (specialy in the late stages). 

Am I missing something ?

**Comment by XECDesign** [comment]
On my end, it's just wanting things as clean as possible based on general mistrust that these tools will do the right thing (burned too many times by them). I don't think rsync will delete directories, for example. That's unlikely to cause issues, but who knows.

Spindle had a nicer approach - instead of copying all the files, it would keep things within qcow2 images and branch them. That saves some time and disk space, so that would probably be the direction I'd head in. It's not without its own issues though.
