### ISSUE TITLE
Can I add a custom script to my pi-gen

### ISSUE THREAD

**Issue by nbren007** [RPi-Distro/pi-gen#587]
Hi,

I haven't found an answer to this in the spec or on forums.  

I've forked a version of Pi-Gen and added in a script to download .net6 and install.  
`wget -O - https://raw.githubusercontent.com/pjgpetecodes/dotnet6pi/master/install.sh | sudo bash`
That works, so now I'd like to deploy my other files at the same time and install the drivers required for my touch screen.

So I need to run some custom actions on my built Pi which I have scripts to do, but I can't see how to put these into a pi-gen stage.

For example if I wanted to copy and run a 'make' to generate some drivers after installing raspberrypi-kernel-headers, how would I do that?  Perhaps I need a post build script that runs at the end?

If running manually on a Pi, I'd do this:
```
cd "${ROOTFS_DIR}/home/pi/focaltech_touch/DTS_Overlay"
dtc -@ -I dts -O dtb -o ft5x06.dtbo ft5x06.dts
sudo cp ft5x06.dtbo "${ROOTFS_DIR}/boot/overlays"
cd ..
make
sudo cp focaltech_core.ko "${ROOTFS_DIR}/usr/lib/modules/$(uname -r)"
sudo depmod -a
sudo modprobe focaltech_core
sudo echo 'focaltech_core' | sudo tee -a "${ROOTFS_DIR}/etc/modules"
```

I'm running the whole job from a Azure-Devops Release script.  I have succeeded in this with a basic blank image (with .Net6), but haven't managed to put all my "customisations" on it yet.  I have kiosk modes and all sorts to do and that's before deploying my application on it.

Any steer in the right direction is appreciated.

**Comment by XECDesign** [comment]
You can add a custom stage and name it something like `stage2.5`. You can look at the existing stages for examples. The on_chroot blocks would be of interest, since that's like running something on a pi. Note that there's no need for all that `sudo`, since everything will run as root anyway (and you'd never need to run `sudo echo` in any environment). Also, `uname` won't work, so you'll need to extract the kernel version some other way.
