### ISSUE TITLE
RELEASE environment variable vs. git tag/branch

### ISSUE THREAD

**Issue by benfrancis** [RPi-Distro/pi-gen#645]
Hi,

If I want to build Raspberry Pi OS Buster, what is the difference between specifying a release in the RELEASE environment variable vs. checking out the latest buster tag from git? E.g. https://github.com/RPi-Distro/pi-gen/tree/2022-09-22-raspios-buster

Is it better to build from the master branch and specify RELEASE=buster, or clone the 2022-09-22-raspios-buster tag (or the buster branch) and accept the default?

Thanks

**Comment by XECDesign** [comment]
Since different releases will have different packages available, and we install some packages which are not available in buster, you'll have better luck building from those tags or the buster branch.

This is a recurring issue, so I'll update the readme and add an appropriate error to pi-gen itself.
